using System;using System.IO;using System.Reflection;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;
public static class BoardRankRender {
 static Texture2D Capture(TabletopBoard stage,RenderTexture rt){typeof(TabletopBoard).GetField("dirty",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(stage,true);stage.Flush();RenderTexture.active=rt;var t=new Texture2D(rt.width,rt.height,TextureFormat.RGB24,false);t.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);t.Apply();RenderTexture.active=null;return t;}
 static int Diff(Texture2D a,Texture2D b){var x=a.GetPixels32();var y=b.GetPixels32();int n=0;for(int i=0;i<x.Length;i++)if(Math.Abs(x[i].r-y[i].r)+Math.Abs(x[i].g-y[i].g)+Math.Abs(x[i].b-y[i].b)>12)n++;return n;}
 public static void Render(){ShaderUtil.allowAsyncCompilation=false;EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);Directory.CreateDirectory("Logs/RankDepth");
 for(int side=0;side<2;side++)foreach(bool zoom in new[]{false,true}){
 var g=new GameObject("Rank depth fixture");var stage=g.AddComponent<TabletopBoard>();var board=new PieceView[100];int from=side==0?60:39,to=side==0?50:49;board[from]=new PieceView{side=side,rank="6"};board[to]=new PieceView{side=1-side,rank="4"};var rt=(RenderTexture)stage.Render(board,side,-1,null,-1,-1,zoom?1000:1400,zoom?1000:899);
 var numbers=(TextMesh[])typeof(TabletopBoard).GetField("numbers",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(stage);var font=numbers[0].font;var fixedMaterial=numbers[0].GetComponent<Renderer>().sharedMaterial;Debug.Log("RANK_DEPTH_MATERIAL legacy="+font.material.shader.name+" queue="+font.material.renderQueue+" fixed="+fixedMaterial.shader.name+" queue="+fixedMaterial.renderQueue+" parent="+numbers[0].transform.parent.name+" local="+numbers[0].transform.localPosition+" bounds="+numbers[side==0?to:99-to].GetComponent<Renderer>().bounds);
 foreach(bool legacy in new[]{true,false}){foreach(var text in numbers)text.GetComponent<Renderer>().sharedMaterial=legacy?font.material:fixedMaterial;stage.Render(board,side,-1,null,-1,-1,rt.width,rt.height);stage.AnimateMove(from,to,side,1,.4f);var overlap=Capture(stage,rt);File.WriteAllBytes("Logs/RankDepth/side"+side+"-"+zoom+"-"+(legacy?"before":"after")+".png",overlap.EncodeToPNG());UnityEngine.Object.DestroyImmediate(overlap);}
 // A broad opaque occluder separates depth behavior from tile height or label bounds.
 var blocker=GameObject.CreatePrimitive(PrimitiveType.Cube);blocker.layer=30;blocker.transform.position=new Vector3(0,3,0);blocker.transform.localScale=new Vector3(30,.1f,30);var mat=new Material(Resources.Load<Shader>("Tabletop"));mat.color=Color.gray;blocker.GetComponent<Renderer>().sharedMaterial=mat;
 foreach(var text in numbers)text.GetComponent<Renderer>().enabled=false;var none=Capture(stage,rt);
 foreach(var text in numbers){text.GetComponent<Renderer>().enabled=true;text.GetComponent<Renderer>().sharedMaterial=font.material;}var old=Capture(stage,rt);
 foreach(var text in numbers)text.GetComponent<Renderer>().sharedMaterial=fixedMaterial;var corrected=Capture(stage,rt);int oldDiff=Diff(none,old),newDiff=Diff(none,corrected);Debug.Log("RANK_DEPTH_PIXELS side="+side+" zoom="+zoom+" legacy="+oldDiff+" corrected="+newDiff);if(oldDiff<10||newDiff!=0)throw new Exception("Depth occlusion regression");
 UnityEngine.Object.DestroyImmediate(blocker);UnityEngine.Object.DestroyImmediate(mat);var visible=Capture(stage,rt);foreach(var text in numbers)text.GetComponent<Renderer>().enabled=false;var invisible=Capture(stage,rt);if(Diff(visible,invisible)<10)throw new Exception("Visible ranks missing");foreach(var image in new[]{none,old,corrected,visible,invisible})UnityEngine.Object.DestroyImmediate(image);UnityEngine.Object.DestroyImmediate(g);
 }Debug.Log("RANK_DEPTH_RENDER_COMPLETE");}
}
