import test from 'node:test';import assert from 'node:assert/strict';import {planDemoMoves as plan} from '../tools/demo-policy.mjs';import {planDemoMoves as browserPlan} from '../browser/engine/demo-policy.mjs';import {createMatch,move,view,acknowledge} from '../server/game.mjs';
const pools=p=>[...p.candidates,...p.fallback,...p.emergency];
function earned(side,row){const m=createMatch(['a','b']),flip=i=>side===0?i:99-i,to=row*10+4,from=to+10;m.phase='play';m.turn=side;m.ready=[true,true];for(const[i,s,rank,id]of[[from,side,'3','hunter'],[to,1-side,'B','bomb'],[5,1-side,'F','flag'],[6,side,'3','other'],[99,1-side,'6','spare']])m.board[flip(i)]={side:s,rank,id};move(m,side,flip(from),flip(to),m.seq,'clear');acknowledge(m,0,m.seq);acknowledge(m,1,m.seq);return{m,flip,at:flip(to)};}
function ownView(m,side){for(const e of m.events)if(e.kind==='combat'){e.ack??=[true,true];e.released??=[true,true];}const v=view(m,side);for(const p of v.board)if(p&&p.side!==side)Object.defineProperty(p,'rank',{get(){throw Error('Hidden rank read')}});return v;}
for(const side of [0,1])for(const row of [0,1])test('side '+side+' earns hunt from rear row '+row+' with own observed victory',()=>{const{m,flip,at}=earned(side,row);let v=ownView(m,side),p=plan(v);assert.equal(Object.keys(p.memory.hunters).length,1);assert.deepEqual(browserPlan(v),p);const id=Object.keys(p.memory.hunters)[0];assert.equal(p.memory.miners[id],at);if(row===1){m.board[flip(4)]=m.board[at];m.board[at]=null;m.events.push({kind:'move',side,from:at,to:flip(4),seq:++m.seq});v=ownView(m,side);p=plan(v,JSON.parse(JSON.stringify(p.memory)));}assert(p.candidates.some(c=>c.from===flip(4)&&c.to===flip(5)));assert(!pools(p).some(c=>c.from===flip(6)&&c.to===flip(5)));const legacy=JSON.parse(JSON.stringify(p.memory));delete legacy.hunters;assert.deepEqual(plan(v,legacy).memory.hunters,p.memory.hunters);const repeat=plan(v,JSON.parse(JSON.stringify(p.memory)));assert.deepEqual(repeat.memory.hunters,p.memory.hunters);assert.equal(Object.keys(plan({...v,id:'fresh',events:[]},p.memory).memory.hunters).length,0);
// Permission stays with this moving survivor, not another Miner taking its square.
const hunterFrom=flip(4);m.board[hunterFrom]=null;m.events.push({kind:'combat',side:1-side,from:flip(14),to:hunterFrom,attacker:'6',defender:'3',outcome:0,seq:++m.seq});m.board[hunterFrom]=m.board[flip(6)];m.board[flip(6)]=null;m.events.push({kind:'move',side,from:flip(6),to:hunterFrom,seq:++m.seq});const after=plan(ownView(m,side),p.memory);assert.equal(Object.keys(after.memory.hunters).length,0);assert(!pools(after).some(c=>c.to===flip(5)));});
test('no trigger for midfield Bomb, other rank victory, or missing observed victory',()=>{for(const side of [0,1]){const{m}=earned(side,2);assert.equal(Object.keys(plan(ownView(m,side)).memory.hunters).length,0);const f=earned(side,0),v=ownView(f.m,side);for(const events of [[],v.events.map(e=>({...e,attacker:'2'})),v.events.map(e=>({...e,outcome:-1}))])assert.equal(Object.keys(plan({...v,decisionMemory:null,events}).memory.hunters).length,0);}});
test('hunter can attack known strong or unknown back-row target in every pool, never unknown target off that row',()=>{for(const side of [0,1]){const{m,flip}=earned(side,0);m.board[flip(14)]={id:'outside',side:1-side,rank:'4'};m.events.push({kind:'combat',side,from:flip(15),to:flip(5),attacker:'2',defender:'10',outcome:-1,seq:++m.seq});let p=plan(ownView(m,side));assert(p.candidates.some(c=>c.from===flip(4)&&c.to===flip(5)));assert(p.fallback.some(c=>c.from===flip(4)&&c.to===flip(5)));assert(!pools(p).some(c=>c.from===flip(4)&&c.to===flip(14)));}});
