import test from 'node:test';import assert from 'node:assert/strict';import {planDemoMoves as plan} from '../tools/demo-policy.mjs';import {planDemoMoves as browserPlan} from '../browser/engine/demo-policy.mjs';import {createMatch,legal} from '../server/game.mjs';import {initTurn,tickTurn} from '../server/turn-clock.mjs';
function fixture(own,rank,side=0){const at=i=>side===0?i:99-i,board=Array(100).fill(null);board[at(60)]={side,rank:own};board[at(50)]={side:1-side,get rank(){throw Error('Hidden rank read')}};const event=rank==='1'?{kind:'combat',side:1-side,from:at(40),to:at(50),attacker:'1',defender:'10',outcome:1,seq:3}:{kind:'combat',side,from:at(40),to:at(50),attacker:'1',defender:rank,outcome:-1,seq:3};return{id:'targets',side,seq:3,board,events:rank==='?'?[]:[event]};}
const all=p=>[...p.candidates,...p.fallback,...p.emergency];
test('both factions: miner attack whitelist applies to every fallback pool, including last miner',()=>{for(const side of [0,1])for(const rank of ['1','2','3','4','5','6','7','8','9','10','B','F','?']){const m=fixture('3',rank,side),p=plan(m),target=side===0?50:49;assert.deepEqual(browserPlan(m),p);assert.equal(all(p).some(c=>c.to===target),['1','2','B'].includes(rank),rank);if(['1','2','B'].includes(rank))assert(p.candidates.some(c=>c.to===target));}});
test('marshal favors known 2-9, rejects known Spy/Bomb and trades 10 only after observed enemy Spy death',()=>{for(const side of [0,1]){const target=side===0?50:49;for(const rank of ['1','2','9','10','B','F','?']){const m=fixture('10',rank,side),p=plan(m);assert.deepEqual(browserPlan(m),p);assert.equal(all(p).some(c=>c.to===target),!['1','10','B'].includes(rank),rank);if(['2','9','F'].includes(rank))assert.equal(p.candidates[0].to,target);}
const m=fixture('10','10',side);m.events.unshift({kind:'combat',seq:2,side,from:70,to:71,attacker:'4',defender:'1',outcome:1});let p=plan(m);assert(p.memory.enemySpyEliminated);assert.equal(p.candidates[0].to,target);let memory=JSON.parse(JSON.stringify(p.memory));m.events=[];m.seq++;p=plan(m,memory);assert(p.memory.enemySpyEliminated);assert.equal(plan({...m,id:'new'},memory).memory.enemySpyEliminated,false);
const ownDeath=fixture('10','10',side);ownDeath.events.unshift({kind:'combat',seq:2,side,from:70,to:71,attacker:'1',defender:'4',outcome:-1});assert(!plan(ownDeath).memory.enemySpyEliminated);assert(!all(plan(ownDeath)).some(c=>c.to===target));}});
test('strict NPC timeout holds safely if only forbidden miner attacks remain; human rules unchanged',()=>{for(const npc of [true,false]){const m=createMatch(['a','b']);m.phase='play';for(const[i,side,rank]of[[60,0,'3'],[61,0,'B'],[70,0,'B'],[50,1,'4']])m.board[i]={id:String(i),side,rank};assert(legal(m,0,60,50));initTurn(m);for(const now of [0,2000,32000,35000])tickTurn(m,'active',now,npc);if(npc){assert.equal(m.seq,0);assert.equal(m.phase,'play');assert.equal(m.turnClock.remaining,30000);}else assert.equal(m.seq,1);}});
for(const module of ['../server/server.mjs','../browser/engine/authority.mjs'])test(module+' NPC metadata activates strict timeout filter',async()=>{const {createAuthority}=await import(module);let now=100000;const a=createAuthority({classCode:'SAFE',teacherKey:'fixture',now:()=>now,timedSetup:false});const seats=[0,1].map(()=>a.call('join',{classCode:'SAFE'}));a.call('teacher/start',{},'fixture');const m=[...a.matches.values()][0],seat=seats.find(p=>p.player===m.players[0]);a.call('teacher/npc',{a:seat.player},'fixture');m.phase='play';m.ready=[true,true];m.board=Array(100).fill(null);for(const[i,side,rank]of[[60,0,'3'],[61,0,'B'],[70,0,'B'],[50,1,'4']])m.board[i]={id:String(i),side,rank};initTurn(m);for(const offset of [0,2000,32000,35000]){now=100000+offset;a.tick();}assert.equal(m.seq,0);assert.equal(m.phase,'play');assert.equal(a.call('state',{},seat.token).match.turnClock.remainingMs,30000);});
