import test from 'node:test';import assert from 'node:assert/strict';
import {fillFormation,flagFormation,shuffleRemaining} from '../web/formation.mjs';
import {COUNTS} from '../server/game.mjs';import {createAuthority} from '../browser/engine/authority.mjs';
const counts=d=>Object.fromEntries(Object.keys(COUNTS).map(r=>[r,d.filter(x=>x===r).length]));
function fixture(){let now=100000;const a=createAuthority({classCode:'PHASE',teacherKey:'teacher',now:()=>now});const seats=[0,1].map(()=>a.call('join',{classCode:'PHASE'}));a.call('teacher/start',{},'teacher');const call=(side,route,b={})=>a.call(route,{matchId:[...a.matches.keys()][0],...b},seats[side].token);return{a,seats,call,advance:ms=>now+=ms};}
const next=(f,side)=>f.call(side,'setup/next',{revision:f.call(side,'state').match.setup.revision});
test('seeded phased fill preserves every occupied square and exact inventory with crowded scout row',()=>{for(let seed=1;seed<=256;seed++){let d=flagFormation(seed);assert.equal(d.filter(Boolean).length,1);assert(d.indexOf('F')>=30);d[d.indexOf('F')]=null;d[0]='F';d=fillFormation(d,2,seed);assert.equal(d[0],'F');assert.equal(d.filter(x=>x==='B').length,6);assert.equal(d.filter(Boolean).length,7);const before=[...d];const full=fillFormation(d,3,seed);assert.deepEqual(counts(full),COUNTS);before.forEach((r,i)=>{if(r)assert.equal(full[i],r);});assert.equal(full.slice(0,10).filter(r=>r==='2').length,Math.min(8,before.slice(0,10).filter(r=>!r).length));const shuffled=shuffleRemaining(full,seed+1);before.forEach((r,i)=>{if(r)assert.equal(shuffled[i],r);});assert.deepEqual(counts(shuffled),COUNTS);}let d=Array(40).fill(null);d[0]='F';for(let i=1;i<7;i++)d[i]='B';d=fillFormation(d,3,123);assert.equal(d.slice(0,10).filter(x=>x==='2').length,3);assert.deepEqual(counts(d),COUNTS);});
test('three stages share one deadline, allow earlier piece edits, and reject skipped/stale transitions',()=>{const f=fixture();let m=f.call(0,'setup/begin').match;const deadline=m.setup.deadline;assert.equal(m.setup.stage,1);assert.throws(()=>f.call(0,'setup',{revision:0}),/three/);let flag=m.setup.draft.indexOf('F');m=f.call(0,'setup/swap',{revision:0,from:flag,to:0}).match;f.advance(15000);m=next(f,0).match;assert.equal(m.setup.stage,2);assert.equal(m.setup.draft[0],'F');assert.equal(m.setup.deadline,deadline);assert.throws(()=>f.call(0,'setup/next',{revision:1}),/changed/);m=f.call(0,'setup/swap',{revision:m.setup.revision,from:0,to:9}).match;const chosen=[...m.setup.draft];m=next(f,0).match;assert.equal(m.setup.stage,3);chosen.forEach((r,i)=>{if(r)assert.equal(m.setup.draft[i],r);});assert.equal(m.setup.remainingMs,285000);assert.throws(()=>next(f,0),/final/);m=f.call(0,'setup/swap',{revision:m.setup.revision,from:9,to:20}).match;assert.equal(m.setup.draft[20],'F');m=f.call(0,'setup',{revision:m.setup.revision}).match;assert.equal(m.ready[m.side],true);assert.equal(m.phase,'setup');});
for(const stage of [1,2,3])test('timeout stage '+stage+' fills only missing pieces and locks once',()=>{const f=fixture();let m=f.call(0,'setup/begin').match;while(m.setup.stage<stage)m=next(f,0).match;const before=[...m.setup.draft],side=m.side;f.advance(300000);f.a.tick();m=f.call(0,'state').match;assert(m.ready[side]);assert(m.setup.automatic);const ranks=Array.from({length:40},(_,k)=>m.board[side===0?60+k:39-k].rank);assert.deepEqual(counts(ranks),COUNTS);before.forEach((r,i)=>{if(r)assert.equal(ranks[i],r);});const seq=m.seq;f.a.tick();assert.equal(f.call(0,'state').match.seq,seq);});
test('recovery restores stage and partial draft; pause/end and both-player readiness remain enforced',()=>{const f=fixture();f.call(0,'setup/begin');next(f,0);f.advance(1234);const before=f.call(0,'state').match.setup;const b=createAuthority({classCode:'PHASE',teacherKey:'teacher',snapshot:f.a.exportSnapshot(),now:()=>101234});assert.deepEqual(b.call('state',{},f.seats[0].token).match.setup,before);assert.equal(f.call(1,'state').match.setup.stage,1);assert.equal(f.call(1,'state').match.board.filter(Boolean).length,0);f.a.call('teacher/pause',{},'teacher');f.advance(999999);assert.equal(f.call(0,'state').match.setup.remainingMs,before.remainingMs);assert.throws(()=>next(f,0),/not enabled/);f.a.call('teacher/resume',{},'teacher');f.call(1,'setup/begin');f.advance(300000);f.a.tick();assert(f.call(0,'state').match.ready.every(Boolean));assert.equal(f.call(0,'state').match.phase,'play');f.a.call('teacher/end',{},'teacher');assert.throws(()=>next(f,0));});
test('NPC setup uses existing full shuffle, teacher-only metadata and cannot be spoofed by student',()=>{const f=fixture(),p=f.seats[1];assert.throws(()=>f.a.call('teacher/npc',{a:p.player},p.token),/Teacher/);f.a.call('teacher/npc',{a:p.player},'teacher');const id=[...f.a.matches.keys()][0];f.a.call('teacher/setup-npc',{a:p.player,matchId:id},'teacher');const m=f.call(1,'state').match,side=m.side,ranks=Array.from({length:40},(_,k)=>m.board[side===0?60+k:39-k].rank);assert.deepEqual(counts(ranks),COUNTS);const flag=ranks.indexOf('F');assert(flag>=30);assert.equal(ranks[flag-10],'B');assert.equal(ranks.slice(0,10).filter(r=>r==='2').length,8);assert.equal(m.ready[side],true);assert.equal(m.ready[1-side],false);assert.equal(m.npc,undefined);assert(!m.playerNames.some(n=>n.includes('(NPC)')));assert(f.a.call('teacher/state',{},'teacher').roster.find(x=>x.id===p.player).npc);assert(f.a.call('teacher/spectate',{matchId:id},'teacher').match.npc[side]);const restored=createAuthority({classCode:'PHASE',teacherKey:'teacher',snapshot:f.a.exportSnapshot(),now:()=>100000});assert(restored.call('teacher/state',{},'teacher').roster.find(x=>x.id===p.player).npc);f.call(0,'setup/begin');f.advance(300000);f.a.tick();assert.equal(f.call(0,'state').match.phase,'play');});

test('browser NPC controller registers actual flag and finishes original shuffle while human stays in phase one',async()=>{
 const {createOpponent}=await import('../browser/npc.mjs');let now=100000;const a=createAuthority({classCode:'BOT',teacherKey:'teacher',now:()=>now});const human=a.call('join',{classCode:'BOT'}),bot=createOpponent(a,'teacher','BOT');
 try{a.call('teacher/start',{},'teacher');const until=Date.now()+2500;let roster;
 do{await new Promise(r=>setTimeout(r,100));roster=a.call('teacher/state',{},'teacher');}while(![...a.matches.values()][0].ready.some(Boolean)&&Date.now()<until);
 const m=a.call('state',{},human.token).match;assert(!m.ready[m.side]);assert(m.ready[1-m.side]);assert.equal(m.setup.stage,1);assert.equal(m.setup.started,false);assert.equal(roster.roster.filter(p=>p.npc).length,1);const recovery=createAuthority({classCode:'BOT',teacherKey:'teacher',snapshot:a.exportSnapshot(),now:()=>now});assert.equal(recovery.call('teacher/state',{},'teacher').roster.filter(p=>p.npc).length,1);
 }finally{bot.stop();}
});
