import test from 'node:test';import assert from 'node:assert/strict';
import {createSolo,SOLO_KEY} from '../browser/solo.mjs';
function fixture(storage){const data=storage??new Map();let time=0,visible=true,tick,stopped=0;const store={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};let botAccess;
 const options={storage:store,now:()=>time,visible:()=>visible,schedule:f=>(tick=f,1),cancel:()=>{},opponentFactory:(a,key,code,token,policy)=>{const s=a.call('state',{},token);a.call('teacher/npc',{a:s.player},key);botAccess={a,token,policy};return {stop:()=>stopped++};}};
 const runtime=createSolo(options);return {runtime,data,options,get bot(){return botAccess},advance(ms){time+=ms;tick()},hide(){visible=false},show(){visible=true},get stopped(){return stopped}};
}
test('solo starts active with distinct opposing generals, NPC ready and human VS intro',()=>{const f=fixture();try{const s=f.runtime.request('join');assert.equal(s.phase,'active');assert.equal(s.paired,true);assert.equal(s.match.phase,'setup');assert.equal(s.match.setup.started,false);assert.deepEqual(s.match.ready,[false,true]);assert.notEqual(s.match.commanders[0].id,s.match.commanders[1].id);assert.deepEqual(s.match.commanders.map(c=>c.side),[0,1]);assert(s.match.commanders.every(c=>/general/i.test(c.role)));assert(s.match.board.every(p=>!p||p.side===s.match.side||p.rank==='?'));}finally{f.runtime.close()}});
test('solo request surface rejects teacher commands and cannot switch identity',()=>{const f=fixture();try{const a=f.runtime.request('join');assert.throws(()=>f.runtime.request('teacher/state'),/unavailable/);assert.throws(()=>f.runtime.request('teacher/spectate'),/unavailable/);assert.equal(f.runtime.request('state',{},f.bot.token).player,a.player);assert.equal('authority' in f.runtime,false);}finally{f.runtime.close()}});
test('three setup stages and reload preserve same seat, draft, clock and hidden ranks',()=>{const f=fixture();let m=f.runtime.request('state').match;f.runtime.request('setup/begin',{matchId:m.id});f.advance(1000);m=f.runtime.request('setup/next',{matchId:m.id,revision:0}).match;assert.equal(m.setup.stage,2);const player=f.runtime.request('state').player,draft=m.setup.draft,remaining=m.setup.remainingMs;f.hide();f.advance(1000000);assert.equal(f.runtime.request('state').match.setup.remainingMs,remaining);f.runtime.close();assert.equal(f.stopped,1);
 const g=fixture(f.data);try{m=g.runtime.request('state').match;assert.equal(g.runtime.request('state').player,player);assert.deepEqual(m.setup.draft,draft);assert.equal(m.setup.remainingMs,remaining);m=g.runtime.request('setup/next',{matchId:m.id,revision:m.setup.revision}).match;assert.equal(m.setup.stage,3);m=g.runtime.request('setup',{matchId:m.id,revision:m.setup.revision}).match;assert.equal(m.phase,'play');assert(m.board.every(p=>!p||p.side===m.side||p.rank==='?'));assert.equal(m.board.filter(Boolean).length,80);}finally{g.runtime.close()}});
test('closing solo rejects delayed bot requests and human commands; no revival',()=>{const f=fixture();f.runtime.close();assert.equal(f.bot.policy.isActive(),false);assert.throws(()=>f.bot.a.call('state',{},f.bot.token),/closed/);assert.throws(()=>f.runtime.request('join'),/closed/);f.runtime.close();assert.equal(f.stopped,1)});
test('NPC policy memory survives refresh while page never receives the private checkpoint',async()=>{const f=fixture();await f.bot.policy.persist({knownBombs:[8]});f.runtime.close();const g=fixture(f.data);try{assert.deepEqual(g.bot.policy.initialMemory,{knownBombs:[8]});assert.equal(g.runtime.request('state').snapshot,undefined);}finally{g.runtime.close()}});
test('bad checkpoint is rejected with actionable restart, not silently overwritten',()=>{const data=new Map([[SOLO_KEY,'bad-json']]);assert.throws(()=>fixture(data),/New solo game/);assert.equal(data.get(SOLO_KEY),'bad-json')});
