import http from 'node:http';import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';
import {launchBrowser} from './browser-helper.mjs';import {tileUV} from './tile-projection.mjs';import {createSolo,SOLO_KEY} from '../browser/solo.mjs';
const root=resolve(process.env.HISTORY_VISUAL_BUILD || 'Builds/SoloPublic/docs'),mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.wasm':'application/wasm','.json':'application/json'};
const server=http.createServer(async(req,res)=>{try{const p=decodeURIComponent(new URL(req.url,'http://localhost').pathname),f=resolve(root,p==='/'?'index.html':'.'+p);assert(f.startsWith(root+'\\'));res.setHeader('Content-Type',mime[extname(f)]||'application/octet-stream');res.end(await readFile(f));}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));
const base='http://127.0.0.1:'+server.address().port,sleep=ms=>new Promise(r=>setTimeout(r,ms));let browser,page;
const init=`window.confirm=()=>true;const raw=window.fetch.bind(window);window.externalFetches=[];window.fetch=(url,...args)=>{const u=new URL(typeof url==='string'?url:url.url,location.href);if(u.origin!==location.origin){window.externalFetches.push(u.href);throw Error('External service blocked');}return raw(url,...args);};if(!sessionStorage.getItem('qa-seeded')){sessionStorage.setItem('qa-seeded','1');sessionStorage.setItem('studentToken','preserve-classroom-token');sessionStorage.setItem('studentTokenClass','KEEP-0123456789ABCDEF');sessionStorage.setItem('history.browserSession',JSON.stringify({role:'teacher',code:'KEEP'}));}`;
const wait=async(fn,label,ms=25000)=>{const end=Date.now()+ms;while(Date.now()<end){if(await fn())return;await sleep(150);}throw Error('Timeout '+label);};
const state=()=>page.evaluate("window.historyClassroom.request('state')");
const canvas=async(x,y)=>page.evaluate(`(()=>{const r=document.querySelector('canvas').getBoundingClientRect(),s=Math.min(r.width/1200,r.height/900);return{x:r.left+(r.width-1200*s)/2+${x}*s,y:r.top+(r.height-900*s)/2+${y}*s}})()`);
const tap=async(q)=>{await page.call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...q});await sleep(90);await page.call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...q});await sleep(200);};
const square=async(i,side,piece=true)=>{const [u,v]=tileUV(i,side,1400/899,piece);await tap(await canvas(25+u*865,178+(1-v)*555));};
function winningCheckpoint(){const mem=new Map(),storage={getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v)};const run=createSolo({storage,visible:()=>true,schedule:()=>1,cancel:()=>{},opponentFactory:(a,key,code,token)=>{const s=a.call('state',{},token);a.call('teacher/npc',{a:s.player},key);return{stop(){}};}});run.close();const saved=JSON.parse(mem.get(SOLO_KEY)),m=saved.snapshot.matches[0];m.phase='play';m.ready=[true,true];m.board=Array(100).fill(null);m.board[60]={id:'human',side:0,rank:'6'};m.board[50]={id:'flag',side:1,rank:'F'};m.board[99]={id:'human-spare',side:0,rank:'2'};m.board[0]={id:'npc-spare',side:1,rank:'2'};m.turn=0;m.seq=0;m.winner=-1;m.events=[];m.history=[[],[]];m.requests=[];m.reveal=null;m.selection=null;delete m.setupClocks;delete m.turnClock;return JSON.stringify(saved);}
try{
 browser=await launchBrowser();page=await browser.page(base+'/student.html?qa=1',{width:1600,height:900,blockSdk:true,initScript:init});await page.call('Network.setBlockedURLs',{urls:['*esm.sh*','*joinplayroom.com*','*playroomkit*']});
 await page.screenshot('Logs/solo-entry.png');assert(await page.evaluate("!!document.querySelector('#solo')"));
 await page.evaluate("document.querySelector('#solo').click()");await page.wait('!!window.unityInstance',120000);await wait(async()=>!!(await state()).match,'intro');await sleep(1800);let s=await state();const original=s.match.id;
 assert.equal(s.phase,'active');assert.equal(s.match.setup.started,false);assert.equal(s.match.ready[1-s.match.side],true);await page.screenshot('Logs/solo-vs.png');
 await tap(await canvas(600,794));await wait(async()=>(await state()).match.setup.started,'begin setup');await tap(await canvas(1040,815));await wait(async()=>(await state()).match.setup.stage===2,'stage 2');const before=(await state()).match.setup.draft;
 await page.call('Page.reload');await page.wait('!!window.unityInstance',120000);await sleep(1600);s=await state();assert.equal(s.match.id,original);assert.deepEqual(s.match.setup.draft,before);assert.equal(s.match.setup.stage,2);await page.screenshot('Logs/solo-reload-phase2.png');
 await tap(await canvas(1040,815));await wait(async()=>(await state()).match.setup.stage===3,'stage 3');await tap(await canvas(1040,815));await wait(async()=>(await state()).match.phase==='play','play');await sleep(3000);s=await state();assert(s.match.board.every(p=>!p||p.side===s.match.side||p.rank==='?'));await page.screenshot('Logs/solo-play.png');
 await page.evaluate("unityInstance.SendMessage('HistoryGame','ToggleBoardFocus')");await page.wait('window.historyBoardFocusActive===true');await sleep(400);await page.screenshot('Logs/solo-zoom.png');await page.evaluate("unityInstance.SendMessage('HistoryGame','ToggleBoardFocus')");await page.wait('window.historyBoardFocusActive===false');
 const from=s.match.board.findIndex((p,i)=>p?.side===s.match.side&&p.rank==='2'&&i>=60&&i<70&&[0,1,4,5,8,9].includes(i%10));assert(from>=0);
 await page.call('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await square(from,s.match.side);await wait(async()=>(await state()).match.selection?.from===from,'select');s=await state();const to=s.match.selection.targets.find(t=>!t.attack).to,seq=s.match.seq;await square(to,s.match.side,false);await wait(async()=>(await state()).match.seq>seq,'human move offline');await wait(async()=>(await state()).match.seq>seq+1,'NPC response offline',25000);await page.screenshot('Logs/solo-offline-npc-response.png');
 await page.call('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});assert.deepEqual(await page.evaluate('window.externalFetches'),[]);assert(!(await page.evaluate("performance.getEntriesByType('resource').map(r=>r.name)")).some(u=>/esm\.sh|joinplayroom|transport\.mjs/.test(u)));
 await page.evaluate(`window.historyClassroom.close();sessionStorage.setItem(${JSON.stringify(SOLO_KEY)},${JSON.stringify(winningCheckpoint())})`);await page.call('Page.reload');await page.wait('!!window.unityInstance',120000);await sleep(1800);s=await state();assert.equal(s.match.board[50].rank,'?');
 await square(60,0);await wait(async()=>(await state()).match.selection?.from===60,'winning selection');await square(50,0,true);await wait(async()=>(await state()).match.battle?.kind==='combat','flag combat');await sleep(1900);await page.screenshot('Logs/solo-flag-combat.png');await wait(async()=>{const v=await state();return v.match.phase==='over'&&!v.match.battle;},'win and both acknowledgements',25000);await sleep(1200);await page.screenshot('Logs/solo-win.png');const won=(await state()).match.id;
 await tap(await canvas(600,565));await wait(async()=>page.evaluate('!!window.unityInstance&&!!window.historyClassroom'),'replay reload',120000);await sleep(2000);await wait(async()=>{try{return (await state()).match.id!==won}catch{return false}},'new match');assert.equal((await state()).match.setup.started,false);
 await page.evaluate("document.querySelector('#solo-return').click()");await page.wait('document.querySelector("#entry")?.hidden===false');await sleep(500);assert.equal(await page.evaluate("sessionStorage.getItem('studentToken')"),'preserve-classroom-token');assert.equal(await page.evaluate("sessionStorage.getItem('studentTokenClass')"),'KEEP-0123456789ABCDEF');assert.equal(await page.evaluate('!!window.historyClassroom'),false);
 const exceptions=page.logs.filter(e=>e.method==='Runtime.exceptionThrown');assert.equal(exceptions.length,0);await writeFile('Logs/solo-browser-result.json',JSON.stringify({passed:true,vsIntro:true,threeStages:true,reload:true,normalZoom:true,postLoadOfflineHumanAndNPCMove:true,blockedPlayroom:true,noExternalFetches:true,scriptedFlagCombatWin:true,unityReplay:true,returnPreservesClassroomIdentity:true,exceptions:0,livePlayroom:false},null,2));console.log('PASS standalone solo actual Unity flow, blocked services and post-load offline moves');
}catch(e){if(page)await page.screenshot('Logs/solo-failure.png');throw e;}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
